### ISSUE TITLE
[Question] Why user and photo entities have different PK values if they are both "identifies" user.

### ISSUE THREAD

**Issue by yuyokk** [alexdebrie/dynamodb-instagram#18]
Hi @alexdebrie,

Not sure if that's appropriate place to ask a question but would be grateful if you can clarify one item.

Entity Chart contains 

| Entity  |       PK        |  SK |
| ------- | :-------------: | --------------------: |
| User    | USER#<Username> |       USER#<Username> |
| Photo   |  UP#<Username>  |       PHOTO#<PhotoId> |
| Like    |  PL#<PhotoId>   | LIKE#<LikingUsername> |
| Comment |  PC#<PhotoId>   |   COMMENT#<CommentId> |

Why user and photo entities have different PK values instead of having same value e.g. `USER#<Username>` (same for photo/like/comment)? Is it for smaller partitions/faster access?

Thank you!

**Comment by alexdebrie** [comment]
Hey @yuyokk,

With DynamoDB, you want to spread your data across your table by using different partition keys. For me, if I don't access data together, I won't give them the same partition key. Since I never access User + Photo in the same Query, I gave them different partition keys.

Hope that helps!

Alex
